name: build

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: alpine
    container:
      image: fruityloops1/alpine-hakkun
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Compile tools
        run: |
          python sys/tools/setup_sail.py
      - name: Build
        run: |
          cmake -B build -DCMAKE_C_COMPILER_FORCED=TRUE -DCMAKE_CXX_COMPILER_FORCED=TRUE -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}"
          cmake --build build -j $(nproc)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.build_type }}
          path: |
            build/*.nss
            build/main.npdm
            build/*.nso
