function(enable_addons project)
    foreach(addon IN LISTS HAKKUN_ADDONS)
        set(ADDON_DIR ${CMAKE_CURRENT_SOURCE_DIR}/sys/addons/${addon})
        if (NOT IS_DIRECTORY ${ADDON_DIR})
            message(FATAL_ERROR "${addon} is not an addon!")
        endif()

        add_subdirectory(${ADDON_DIR})
        target_include_directories(LibHakkun PRIVATE ${ADDON_DIR}/include)
        target_include_directories(${project} PRIVATE ${ADDON_DIR}/include)
        target_include_directories(${addon} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/sys/hakkun/include)
        target_link_libraries(${project} PRIVATE ${addon})

        target_compile_definitions(${project} PRIVATE HK_ADDON_${addon})
        target_compile_definitions(${addon} PRIVATE HK_ADDON_${addon})
        target_compile_definitions(LibHakkun PRIVATE HK_ADDON_${addon})
        
        message("Enabled addon ${addon}")
    endforeach()

    foreach(addon IN LISTS HAKKUN_ADDONS)
        foreach(saddon IN LISTS HAKKUN_ADDONS)
            if (NOT saddon STREQUAL addon)
                set(ADDON_DIR ${CMAKE_CURRENT_SOURCE_DIR}/sys/addons/${saddon})
                target_include_directories(${addon} PRIVATE ${ADDON_DIR}/include ${ADDON_DIR}/include/hk)
            endif()
            target_compile_definitions(${addon} PRIVATE HK_ADDON_${saddon})
        endforeach()
    endforeach()
endfunction()
