file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/exefs)

if (
    (DEFINED TARGET_IS_STATIC AND TARGET_IS_STATIC)
 OR (HAKKUN_TARGET STREQUAL MODULE_STANDALONE)
    )
    set(COPY_RTLD TRUE)
else()
    set(COPY_RTLD FALSE)
endif()

set(IS_STANDALONE "0")
if (HAKKUN_TARGET STREQUAL MODULE_STANDALONE)
    set(IS_STANDALONE "1")
endif()

if (HAKKUN_TARGET STREQUAL MODULE_DLL)
    if (HOMEBREW_TYPE STREQUAL HBLOADER)
        add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
            COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/sys/tools/deploy.py ${CMAKE_CURRENT_BINARY_DIR} ${PROJECT_NAME} ${HOMEBREW_TYPE}
        )
    endif()
else()
    add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
        COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/sys/tools/deploy.py ${CMAKE_CURRENT_BINARY_DIR} ${PROJECT_NAME} NONE ${TITLE_ID} ${MODULE_BINARY} ${COPY_RTLD} ${IS_STANDALONE}
    )
endif()
