file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/exefs)

if (
    (DEFINED TARGET_IS_STATIC AND TARGET_IS_STATIC)
 OR (DEFINED HAKKUN_STANDALONE AND HAKKUN_STANDALONE)
    )
    set(COPY_RTLD TRUE)
else()
    set(COPY_RTLD FALSE)
endif()

add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/sys/tools/deploy.py ${CMAKE_CURRENT_BINARY_DIR} ${PROJECT_NAME} ${TITLE_ID} ${MODULE_BINARY} ${COPY_RTLD} ${HAKKUN_STANDALONE}
)
